### ISSUE TITLE
Update news system

### ISSUE THREAD

**Issue by iWirk** [emodyz/MultigamingPanel#47]
Requested by @leohubert 

- [x] 1. Pouvoir unpublish une news 

- [x] 2. Dans les seeder, avoir une image par news. (ce qui évite l'effacement de l'image de toutes les news lors de l'update d'une image d'un article vu que c'est la même image / url)

- [x] 3. Pouvoir définir le nombre de news aussi pour les articles d'un serveur

**Comment by leohubert** [comment]
Done
